---
name: module3_task1
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
jobs:
  validate:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Makefile help command
        run: cd ./module3_task1/ && make help

      - name: setup
        run: cd ./module3_task1/ &&  sudo ./setup.sh

      - name: Validate Makefile build command
        run: cd ./module3_task1/ && make build

      - name: Validate Makefile test command
        run: cd ./module3_task1/ && make test

      - name: Validate Makefile run command
        run: cd ./module3_task1/ && make run

      - name: Validate Makefile clean command
        run: cd ./module3_task1/ && make clean
